/* Generated by Yosys 0.67+135 (git sha1 ac5910309-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module clkdiv_mcp(clk, rst_n, operand, accept, acc_out, clk_div2_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [31:0] operand;
  wire [31:0] operand;
  input accept;
  wire accept;
  output [31:0] acc_out;
  wire [31:0] acc_out;
  output clk_div2_out;
  wire clk_div2_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire [31:0] acc;
  wire clk_div2;
  sky130_fd_sc_hd__clkinv_1 _249_ (
    .A(accept),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21ai_0 _250_ (
    .A1(acc[25]),
    .A2(operand[25]),
    .B1(operand[26]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _251_ (
    .A(acc[25]),
    .B(operand[25]),
    .C(operand[26]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _252_ (
    .A(_034_),
    .SLEEP(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor3_1 _254_ (
    .A(acc[24]),
    .B(operand[25]),
    .C(operand[24]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor3_1 _255_ (
    .A(acc[22]),
    .B(operand[23]),
    .C(operand[22]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__or3_1 _256_ (
    .A(acc[22]),
    .B(operand[23]),
    .C(operand[22]),
    .X(_040_)
  );
  sky130_fd_sc_hd__o21a_1 _257_ (
    .A1(acc[21]),
    .A2(operand[21]),
    .B1(operand[22]),
    .X(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _258_ (
    .A(acc[21]),
    .B(operand[21]),
    .C(operand[22]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or3_1 _260_ (
    .A(acc[20]),
    .B(operand[21]),
    .C(operand[20]),
    .X(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _261_ (
    .A1(acc[19]),
    .A2(operand[19]),
    .B1(operand[20]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _262_ (
    .A(acc[19]),
    .B(operand[19]),
    .C(operand[20]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _263_ (
    .A(_045_),
    .SLEEP(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _264_ (
    .A1(acc[17]),
    .A2(operand[17]),
    .B1(operand[18]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _265_ (
    .A(acc[18]),
    .B(operand[19]),
    .C(operand[18]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__or3_1 _266_ (
    .A(acc[17]),
    .B(operand[17]),
    .C(operand[18]),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(_048_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21a_1 _268_ (
    .A1(acc[13]),
    .A2(operand[13]),
    .B1(operand[14]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _269_ (
    .A(acc[13]),
    .B(operand[13]),
    .C(operand[14]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__or3_1 _270_ (
    .A(acc[12]),
    .B(operand[12]),
    .C(operand[13]),
    .X(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _271_ (
    .A1(acc[11]),
    .A2(operand[11]),
    .B1(operand[12]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__or3_1 _272_ (
    .A(acc[11]),
    .B(operand[11]),
    .C(operand[12]),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _273_ (
    .A(acc[10]),
    .B(operand[11]),
    .C(operand[10]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(acc[9]),
    .A2(operand[9]),
    .B1(operand[10]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor3_1 _275_ (
    .A(acc[9]),
    .B(operand[10]),
    .C(operand[9]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _276_ (
    .A(_058_),
    .SLEEP(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__or3_1 _277_ (
    .A(acc[8]),
    .B(operand[9]),
    .C(operand[8]),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor3_1 _278_ (
    .A(acc[6]),
    .B(operand[6]),
    .C(operand[7]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or3_1 _279_ (
    .A(acc[4]),
    .B(operand[4]),
    .C(operand[5]),
    .X(_063_)
  );
  sky130_fd_sc_hd__nor3_1 _280_ (
    .A(acc[2]),
    .B(operand[3]),
    .C(operand[2]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _281_ (
    .A1(acc[0]),
    .A2(operand[0]),
    .B1(operand[1]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _282_ (
    .A1(acc[1]),
    .A2(operand[1]),
    .B1(operand[2]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _283_ (
    .A1(acc[2]),
    .A2(operand[2]),
    .B1(operand[3]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o311ai_0 _284_ (
    .A1(operand[2]),
    .A2(_064_),
    .A3(_065_),
    .B1(_066_),
    .C1(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21ai_0 _285_ (
    .A1(acc[3]),
    .A2(operand[3]),
    .B1(operand[4]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__or3_1 _286_ (
    .A(acc[3]),
    .B(operand[4]),
    .C(operand[3]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand3_1 _287_ (
    .A(_068_),
    .B(_069_),
    .C(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o21ai_0 _288_ (
    .A1(acc[4]),
    .A2(operand[4]),
    .B1(operand[5]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a41oi_1 _290_ (
    .A1(_063_),
    .A2(_068_),
    .A3(_069_),
    .A4(_070_),
    .B1(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _291_ (
    .A1(acc[5]),
    .A2(operand[5]),
    .B1(operand[6]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _292_ (
    .A(acc[5]),
    .B(operand[6]),
    .C(operand[5]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _293_ (
    .A(_075_),
    .SLEEP(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _294_ (
    .A1(acc[6]),
    .A2(operand[6]),
    .B1(operand[7]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o311ai_0 _295_ (
    .A1(_062_),
    .A2(_074_),
    .A3(_076_),
    .B1(_078_),
    .C1(_075_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ai_0 _296_ (
    .A1(acc[7]),
    .A2(operand[7]),
    .B1(operand[8]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__or3_1 _297_ (
    .A(acc[7]),
    .B(operand[8]),
    .C(operand[7]),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _299_ (
    .A1(acc[8]),
    .A2(operand[8]),
    .B1(operand[9]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(_080_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a41oi_1 _301_ (
    .A1(_061_),
    .A2(_079_),
    .A3(_080_),
    .A4(_081_),
    .B1(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(acc[10]),
    .A2(operand[10]),
    .B1(operand[11]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o311ai_0 _303_ (
    .A1(_057_),
    .A2(_059_),
    .A3(_085_),
    .B1(_086_),
    .C1(_058_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _304_ (
    .A(_055_),
    .B(_056_),
    .C(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _305_ (
    .A1(acc[12]),
    .A2(operand[12]),
    .B1(operand[13]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(_055_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a41oi_1 _307_ (
    .A1(_054_),
    .A2(_055_),
    .A3(_056_),
    .A4(_087_),
    .B1(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor3_1 _308_ (
    .A(_052_),
    .B(_053_),
    .C(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(acc[14]),
    .A2(operand[14]),
    .B1(operand[15]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor3_1 _310_ (
    .A(acc[14]),
    .B(operand[15]),
    .C(operand[14]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _311_ (
    .A(_093_),
    .SLEEP(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o41ai_1 _313_ (
    .A1(_052_),
    .A2(_053_),
    .A3(_091_),
    .A4(_096_),
    .B1(_093_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21a_1 _314_ (
    .A1(acc[15]),
    .A2(operand[15]),
    .B1(operand[16]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor3_1 _315_ (
    .A(acc[15]),
    .B(operand[16]),
    .C(operand[15]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21a_1 _317_ (
    .A1(_052_),
    .A2(_097_),
    .B1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__or3_1 _318_ (
    .A(acc[16]),
    .B(operand[17]),
    .C(operand[16]),
    .X(_102_)
  );
  sky130_fd_sc_hd__o211ai_1 _319_ (
    .A1(_052_),
    .A2(_097_),
    .B1(_100_),
    .C1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(acc[16]),
    .A2(operand[16]),
    .B1(operand[17]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2b_1 _321_ (
    .A(_098_),
    .B_N(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(_102_),
    .B(_104_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21o_1 _323_ (
    .A1(_103_),
    .A2(_105_),
    .B1(_051_),
    .X(_107_)
  );
  sky130_fd_sc_hd__o21ai_0 _324_ (
    .A1(acc[18]),
    .A2(operand[18]),
    .B1(operand[19]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a211oi_1 _325_ (
    .A1(_103_),
    .A2(_105_),
    .B1(_049_),
    .C1(_051_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_048_),
    .B(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_047_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o211a_1 _328_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_044_),
    .C1(_047_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _329_ (
    .A1(acc[20]),
    .A2(operand[20]),
    .B1(operand[21]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_045_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21a_1 _331_ (
    .A1(_112_),
    .A2(_114_),
    .B1(_043_),
    .X(_115_)
  );
  sky130_fd_sc_hd__o211ai_1 _332_ (
    .A1(_112_),
    .A2(_114_),
    .B1(_040_),
    .C1(_043_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21a_1 _333_ (
    .A1(acc[22]),
    .A2(operand[22]),
    .B1(operand[23]),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_041_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__and2_0 _335_ (
    .A(_116_),
    .B(_118_),
    .X(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _336_ (
    .A1(acc[23]),
    .A2(operand[23]),
    .B1(operand[24]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__or3_1 _337_ (
    .A(acc[23]),
    .B(operand[23]),
    .C(operand[24]),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a211o_1 _339_ (
    .A1(_116_),
    .A2(_118_),
    .B1(_122_),
    .C1(_038_),
    .X(_123_)
  );
  sky130_fd_sc_hd__o21ai_0 _340_ (
    .A1(acc[24]),
    .A2(operand[24]),
    .B1(operand[25]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(_120_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_123_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_036_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor3_1 _345_ (
    .A(acc[26]),
    .B(operand[27]),
    .C(operand[26]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a211oi_1 _346_ (
    .A1(_123_),
    .A2(_126_),
    .B1(_129_),
    .C1(_037_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _347_ (
    .A1(acc[26]),
    .A2(operand[26]),
    .B1(operand[27]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_034_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2b_1 _349_ (
    .A(_129_),
    .B_N(_131_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _350_ (
    .A1(acc[27]),
    .A2(operand[27]),
    .B1(operand[28]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__or3_1 _351_ (
    .A(acc[27]),
    .B(operand[27]),
    .C(operand[28]),
    .X(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(_134_),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21ai_0 _354_ (
    .A1(_130_),
    .A2(_132_),
    .B1(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__or3_1 _355_ (
    .A(acc[28]),
    .B(operand[29]),
    .C(operand[28]),
    .X(_139_)
  );
  sky130_fd_sc_hd__o211ai_1 _356_ (
    .A1(_130_),
    .A2(_132_),
    .B1(_137_),
    .C1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _357_ (
    .A1(acc[28]),
    .A2(operand[28]),
    .B1(operand[29]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__and2_0 _358_ (
    .A(_134_),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_139_),
    .B(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _360_ (
    .A(_140_),
    .B(_142_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21a_1 _361_ (
    .A1(acc[29]),
    .A2(operand[29]),
    .B1(operand[30]),
    .X(_145_)
  );
  sky130_fd_sc_hd__nor3_1 _362_ (
    .A(acc[29]),
    .B(operand[29]),
    .C(operand[30]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _363_ (
    .A(_145_),
    .SLEEP(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _364_ (
    .A1(_140_),
    .A2(_142_),
    .B1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xor2_1 _365_ (
    .A(_144_),
    .B(_147_),
    .X(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(accept),
    .A2(acc[30]),
    .B1(rst_n),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _367_ (
    .A1(accept),
    .A2(_149_),
    .B1(_150_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(_134_),
    .B(_138_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__xor2_1 _369_ (
    .A(_143_),
    .B(_151_),
    .X(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _370_ (
    .A1(accept),
    .A2(acc[29]),
    .B1(rst_n),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _371_ (
    .A1(accept),
    .A2(_152_),
    .B1(_153_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__or3_1 _372_ (
    .A(_130_),
    .B(_132_),
    .C(_137_),
    .X(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _373_ (
    .A1(_138_),
    .A2(_154_),
    .B1(_033_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _374_ (
    .A1(accept),
    .A2(acc[28]),
    .B1(rst_n),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(_155_),
    .B(_156_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(_034_),
    .B(_128_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _377_ (
    .A(_133_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o21ai_0 _378_ (
    .A1(accept),
    .A2(acc[27]),
    .B1(rst_n),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _379_ (
    .A1(accept),
    .A2(_158_),
    .B1(_159_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand3_1 _380_ (
    .A(_037_),
    .B(_123_),
    .C(_126_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _381_ (
    .A1(_128_),
    .A2(_160_),
    .B1(_033_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21ai_0 _382_ (
    .A1(accept),
    .A2(acc[26]),
    .B1(rst_n),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _383_ (
    .A(_161_),
    .B(_162_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2b_1 _384_ (
    .A_N(_038_),
    .B(_124_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _385_ (
    .A1(_119_),
    .A2(_122_),
    .B1(_120_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__xor2_1 _386_ (
    .A(_163_),
    .B(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _387_ (
    .A1(accept),
    .A2(acc[25]),
    .B1(rst_n),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _388_ (
    .A1(accept),
    .A2(_165_),
    .B1(_166_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_119_),
    .B(_122_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _390_ (
    .A1(accept),
    .A2(acc[24]),
    .B1(rst_n),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a21oi_1 _391_ (
    .A1(accept),
    .A2(_167_),
    .B1(_168_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__or4_1 _392_ (
    .A(_039_),
    .B(_041_),
    .C(_115_),
    .D(_117_),
    .X(_169_)
  );
  sky130_fd_sc_hd__o22ai_1 _393_ (
    .A1(_041_),
    .A2(_115_),
    .B1(_117_),
    .B2(_039_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o21ai_0 _394_ (
    .A1(accept),
    .A2(acc[23]),
    .B1(rst_n),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a31oi_1 _395_ (
    .A1(accept),
    .A2(_169_),
    .A3(_170_),
    .B1(_171_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3_1 _396_ (
    .A(_043_),
    .B(_112_),
    .C(_114_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__o21ai_0 _397_ (
    .A1(_115_),
    .A2(_172_),
    .B1(accept),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o211a_1 _398_ (
    .A1(accept),
    .A2(acc[22]),
    .B1(rst_n),
    .C1(_173_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_044_),
    .B(_113_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _400_ (
    .A(_045_),
    .B(_111_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xor2_1 _401_ (
    .A(_174_),
    .B(_175_),
    .X(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _402_ (
    .A1(accept),
    .A2(acc[21]),
    .B1(rst_n),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _403_ (
    .A1(accept),
    .A2(_176_),
    .B1(_177_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor3_1 _404_ (
    .A(_047_),
    .B(_109_),
    .C(_110_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__clkinv_1 _405_ (
    .A(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _406_ (
    .A1(_111_),
    .A2(_179_),
    .B1(_033_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(accept),
    .A2(acc[20]),
    .B1(rst_n),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_180_),
    .B(_181_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2b_1 _409_ (
    .A_N(_049_),
    .B(_108_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(_048_),
    .B(_107_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _411_ (
    .A(_182_),
    .B(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _412_ (
    .A1(accept),
    .A2(acc[19]),
    .B1(rst_n),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _413_ (
    .A1(accept),
    .A2(_184_),
    .B1(_185_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand3_1 _414_ (
    .A(_051_),
    .B(_103_),
    .C(_105_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(_107_),
    .B(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21ai_0 _416_ (
    .A1(accept),
    .A2(acc[18]),
    .B1(rst_n),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _417_ (
    .A1(accept),
    .A2(_187_),
    .B1(_188_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _418_ (
    .A(_098_),
    .B(_101_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(_106_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21ai_0 _420_ (
    .A1(accept),
    .A2(acc[17]),
    .B1(rst_n),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _421_ (
    .A1(accept),
    .A2(_190_),
    .B1(_191_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _422_ (
    .A(_052_),
    .B(_097_),
    .C(_100_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _423_ (
    .A1(_101_),
    .A2(_192_),
    .B1(accept),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o211a_1 _424_ (
    .A1(accept),
    .A2(acc[16]),
    .B1(rst_n),
    .C1(_193_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _425_ (
    .A(_052_),
    .B(_092_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__xnor2_1 _426_ (
    .A(_096_),
    .B(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o21ai_0 _427_ (
    .A1(accept),
    .A2(acc[15]),
    .B1(rst_n),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a21oi_1 _428_ (
    .A1(accept),
    .A2(_195_),
    .B1(_196_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o21ai_0 _429_ (
    .A1(_052_),
    .A2(_053_),
    .B1(_091_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand2b_1 _430_ (
    .A_N(_092_),
    .B(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__o21ai_0 _431_ (
    .A1(accept),
    .A2(acc[14]),
    .B1(rst_n),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _432_ (
    .A1(accept),
    .A2(_198_),
    .B1(_199_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_054_),
    .B(_089_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(_055_),
    .B(_088_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__xor2_1 _435_ (
    .A(_200_),
    .B(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd__o21ai_0 _436_ (
    .A1(accept),
    .A2(acc[13]),
    .B1(rst_n),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _437_ (
    .A1(accept),
    .A2(_202_),
    .B1(_203_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21o_1 _438_ (
    .A1(_055_),
    .A2(_056_),
    .B1(_087_),
    .X(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_088_),
    .B(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__o21ai_0 _440_ (
    .A1(accept),
    .A2(acc[12]),
    .B1(rst_n),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a21oi_1 _441_ (
    .A1(accept),
    .A2(_205_),
    .B1(_206_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2b_1 _442_ (
    .A_N(_057_),
    .B(_086_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o21ai_0 _443_ (
    .A1(_059_),
    .A2(_085_),
    .B1(_058_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xor2_1 _444_ (
    .A(_207_),
    .B(_208_),
    .X(_209_)
  );
  sky130_fd_sc_hd__o21ai_0 _445_ (
    .A1(accept),
    .A2(acc[11]),
    .B1(rst_n),
    .Y(_210_)
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(accept),
    .A2(_209_),
    .B1(_210_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _447_ (
    .A(_060_),
    .B(_085_),
    .X(_211_)
  );
  sky130_fd_sc_hd__o21ai_0 _448_ (
    .A1(accept),
    .A2(acc[10]),
    .B1(rst_n),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _449_ (
    .A1(accept),
    .A2(_211_),
    .B1(_212_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_061_),
    .B(_083_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a21boi_0 _451_ (
    .A1(_079_),
    .A2(_081_),
    .B1_N(_080_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__xnor2_1 _452_ (
    .A(_213_),
    .B(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o21ai_0 _453_ (
    .A1(accept),
    .A2(acc[9]),
    .B1(rst_n),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _454_ (
    .A1(accept),
    .A2(_215_),
    .B1(_216_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _455_ (
    .A(_079_),
    .B(_082_),
    .X(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _456_ (
    .A1(accept),
    .A2(acc[8]),
    .B1(rst_n),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a21oi_1 _457_ (
    .A1(accept),
    .A2(_217_),
    .B1(_218_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2b_1 _458_ (
    .A_N(_062_),
    .B(_078_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21ai_0 _459_ (
    .A1(_074_),
    .A2(_076_),
    .B1(_075_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xor2_1 _460_ (
    .A(_219_),
    .B(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__o21ai_0 _461_ (
    .A1(accept),
    .A2(acc[7]),
    .B1(rst_n),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a21oi_1 _462_ (
    .A1(accept),
    .A2(_221_),
    .B1(_222_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _463_ (
    .A(_074_),
    .B(_077_),
    .X(_223_)
  );
  sky130_fd_sc_hd__o21ai_0 _464_ (
    .A1(accept),
    .A2(acc[6]),
    .B1(rst_n),
    .Y(_224_)
  );
  sky130_fd_sc_hd__a21oi_1 _465_ (
    .A1(accept),
    .A2(_223_),
    .B1(_224_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(_063_),
    .B(_072_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(_069_),
    .B(_071_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__xor2_1 _468_ (
    .A(_225_),
    .B(_226_),
    .X(_227_)
  );
  sky130_fd_sc_hd__o21ai_0 _469_ (
    .A1(accept),
    .A2(acc[5]),
    .B1(rst_n),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21oi_1 _470_ (
    .A1(accept),
    .A2(_227_),
    .B1(_228_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21o_1 _471_ (
    .A1(_069_),
    .A2(_070_),
    .B1(_068_),
    .X(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _472_ (
    .A(_071_),
    .B(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o21ai_0 _473_ (
    .A1(accept),
    .A2(acc[4]),
    .B1(rst_n),
    .Y(_231_)
  );
  sky130_fd_sc_hd__a21oi_1 _474_ (
    .A1(accept),
    .A2(_230_),
    .B1(_231_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2b_1 _475_ (
    .A(_064_),
    .B_N(_067_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(_065_),
    .B(_066_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__xnor2_1 _477_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__o21ai_0 _478_ (
    .A1(accept),
    .A2(acc[3]),
    .B1(rst_n),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _479_ (
    .A1(accept),
    .A2(_234_),
    .B1(_235_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _480_ (
    .A1(acc[1]),
    .A2(operand[1]),
    .B1(_065_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__xor2_1 _481_ (
    .A(operand[2]),
    .B(_236_),
    .X(_237_)
  );
  sky130_fd_sc_hd__o21ai_0 _482_ (
    .A1(accept),
    .A2(acc[2]),
    .B1(rst_n),
    .Y(_238_)
  );
  sky130_fd_sc_hd__a21oi_1 _483_ (
    .A1(accept),
    .A2(_237_),
    .B1(_238_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or3_1 _484_ (
    .A(acc[0]),
    .B(operand[1]),
    .C(operand[0]),
    .X(_239_)
  );
  sky130_fd_sc_hd__a21oi_1 _485_ (
    .A1(_065_),
    .A2(_239_),
    .B1(_033_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__o21ai_0 _486_ (
    .A1(accept),
    .A2(acc[1]),
    .B1(rst_n),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nor2_1 _487_ (
    .A(_240_),
    .B(_241_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _488_ (
    .A(accept),
    .B(acc[0]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__o21ai_0 _489_ (
    .A1(_033_),
    .A2(operand[0]),
    .B1(rst_n),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(_242_),
    .B(_243_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _491_ (
    .A(acc[30]),
    .B(operand[30]),
    .Y(_244_)
  );
  sky130_fd_sc_hd__xnor2_1 _492_ (
    .A(operand[31]),
    .B(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__or3b_1 _493_ (
    .A(_145_),
    .B(_148_),
    .C_N(_245_),
    .X(_246_)
  );
  sky130_fd_sc_hd__o21bai_1 _494_ (
    .A1(_145_),
    .A2(_148_),
    .B1_N(_245_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__o21ai_0 _495_ (
    .A1(acc[31]),
    .A2(accept),
    .B1(rst_n),
    .Y(_248_)
  );
  sky130_fd_sc_hd__a31oi_1 _496_ (
    .A1(accept),
    .A2(_246_),
    .A3(_247_),
    .B1(_248_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _497_ (
    .A(rst_n),
    .SLEEP(clk_div2),
    .X(_032_)
  );
  sky130_fd_sc_hd__dfxtp_1 _498_ (
    .CLK(clk_div2),
    .D(_028_),
    .Q(acc[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _499_ (
    .CLK(clk_div2),
    .D(_027_),
    .Q(acc[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _500_ (
    .CLK(clk_div2),
    .D(_026_),
    .Q(acc[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _501_ (
    .CLK(clk_div2),
    .D(_025_),
    .Q(acc[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _502_ (
    .CLK(clk_div2),
    .D(_024_),
    .Q(acc[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _503_ (
    .CLK(clk_div2),
    .D(_023_),
    .Q(acc[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _504_ (
    .CLK(clk_div2),
    .D(_022_),
    .Q(acc[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _505_ (
    .CLK(clk_div2),
    .D(_021_),
    .Q(acc[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _506_ (
    .CLK(clk_div2),
    .D(_020_),
    .Q(acc[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _507_ (
    .CLK(clk_div2),
    .D(_019_),
    .Q(acc[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _508_ (
    .CLK(clk_div2),
    .D(_018_),
    .Q(acc[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _509_ (
    .CLK(clk_div2),
    .D(_017_),
    .Q(acc[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _510_ (
    .CLK(clk_div2),
    .D(_016_),
    .Q(acc[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _511_ (
    .CLK(clk_div2),
    .D(_015_),
    .Q(acc[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _512_ (
    .CLK(clk_div2),
    .D(_014_),
    .Q(acc[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _513_ (
    .CLK(clk_div2),
    .D(_013_),
    .Q(acc[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _514_ (
    .CLK(clk_div2),
    .D(_012_),
    .Q(acc[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _515_ (
    .CLK(clk_div2),
    .D(_011_),
    .Q(acc[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _516_ (
    .CLK(clk_div2),
    .D(_010_),
    .Q(acc[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _517_ (
    .CLK(clk_div2),
    .D(_009_),
    .Q(acc[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _518_ (
    .CLK(clk_div2),
    .D(_008_),
    .Q(acc[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _519_ (
    .CLK(clk_div2),
    .D(_007_),
    .Q(acc[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _520_ (
    .CLK(clk_div2),
    .D(_006_),
    .Q(acc[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _521_ (
    .CLK(clk_div2),
    .D(_005_),
    .Q(acc[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _522_ (
    .CLK(clk_div2),
    .D(_004_),
    .Q(acc[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _523_ (
    .CLK(clk_div2),
    .D(_003_),
    .Q(acc[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _524_ (
    .CLK(clk_div2),
    .D(_002_),
    .Q(acc[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _525_ (
    .CLK(clk_div2),
    .D(_001_),
    .Q(acc[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _526_ (
    .CLK(clk_div2),
    .D(_000_),
    .Q(acc[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _527_ (
    .CLK(clk_div2),
    .D(_031_),
    .Q(acc[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _528_ (
    .CLK(clk),
    .D(_032_),
    .Q(clk_div2)
  );
  sky130_fd_sc_hd__dfxtp_1 _529_ (
    .CLK(clk_div2),
    .D(_030_),
    .Q(acc[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _530_ (
    .CLK(clk_div2),
    .D(_029_),
    .Q(acc[1])
  );
  assign clk_div2_out = clk_div2;
  assign acc_out = acc;
endmodule
