#!/usr/bin/env python3
"""Build the v2/v3 review package: the report and only the evidence it cites.

scripts/package_submission.py froze the 2026-09-11 v1 bundle and still ships
the v1 report and v1 artifact set. This builds the bundle the current report
is actually made of -- the v2 benchmark, the v2 loop runs, the v3 routed PPA,
and the generated fragments every number in the PDF comes from.

Anything listed in REQUIRED must exist or the build fails loudly; the TREES
are copied when present, because some are produced by runs that may still be
in flight.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import zipfile
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED = [
    "README.md",          # generated by scripts/build_readme.py
    "report/nebula_report.pdf",
    "report/nebula_report.tex",
    "report/generated/numbers.tex",
    "report/generated/tab_ppa.tex",
    "report/generated/fig_soc.tex",
    "bench/constraints/nebula.sdc",
    "bench/scripts/loop.py",
    "bench/scripts/metrics.py",
    "bench/scripts/ppa_report.py",
    "artifacts/paths/v2_targets.json",
    "artifacts/clockcheck_v2.json",
    "artifacts/clocksim.json",
    "artifacts/eqy_v2_serial_partial.log",
    "scripts/build_report.py",
    "scripts/build_figures.py",
    "scripts/submission_check_v2.py",
    "scripts/package_submission_v2.py",
    "scripts/build_readme.py",
    "demo_v2.py",
]

ROOT_FILES = [
    "WORKLOG.md",
    # demo.py narrates the v1 run and reads v1 artifacts this bundle does not
    # carry. demo_v2.py (in REQUIRED) is the demo for this submission.
    "Nebula_Abstract.pdf",
    "benchmark.png",
    "domains.pdf",
]

TREES = [
    "report/generated",
    "bench/rtl_v2",
    "bench/constraints",
    "bench/scripts",
    "bench/tb",
    "bench/mock_proposals",
    "scripts",
    "docs",
    "macros",
    "sta/sky130hd",
    "artifacts/bakeoff_v2",
    "artifacts/bakeoff_v2_sonnet_fixed",
    "artifacts/divider_run",
    "artifacts/paths",
    "artifacts/lint_v2",
    "artifacts/eqy/reset_aware_20260911",
    "output/rtl_variants_v2",
    "orfs/flow/designs/sky130hd/nebula_bench_v2",
]

# Newest-wins globs: the run stamps move, the bundle should follow.
NEWEST_TREES = ["artifacts/metrics_v2_*", "artifacts/metrics_v3_*"]

SINGLE_GLOBS = [
    # The shard *directories* are EQY workdirs -- 9.3 GB of solver scratch.
    # The verdicts live in the JSON and log beside them, which is what the
    # report reads and what a reviewer can check.
    "artifacts/eqy/shards/*.json",
    "artifacts/eqy/shards/*.log",
    "artifacts/ppa_v2_*.json",
    "artifacts/ppa_v2_*.md",
    "bench/DECISIONS.md",
    "bench/README.md",
    "report/nebula_report.pdf",
    "report/nebula_report.tex",
]

# Routed evidence for the two v3 runs: reports only, never the odb/def, which
# are gigabytes and reproducible from the flow.
PNR_REPORTS = "artifacts/model_ppa_v3/pnr_*/reports/sky130hd/nebula_bench_v2/*"
PNR_LOGS = "artifacts/model_ppa_v3/pnr_*/logs/sky130hd/nebula_bench_v2/*"

SKIP_NAMES = {".DS_Store", "__pycache__", ".pytest_cache", ".ipynb_checkpoints"}
SKIP_SUFFIX = {".odb", ".def", ".gds", ".lef", ".db", ".pyc", ".guide", ".drc"}
MAX_FILE = 40 << 20          # a single artifact bigger than this is a workdir
MAX_TOTAL = 600 << 20        # whole-bundle ceiling; tripping it means a
                             # workdir got swept in, not that evidence grew

SECRET_PATTERNS = [
    re.compile(rb"(?:GEMINI|OPENROUTER|ANTHROPIC)_API_KEY\s*=\s*\S+"),
    re.compile(rb"sk-or-v1-[A-Za-z0-9_-]{20,}"),
    re.compile(rb"sk-ant-[A-Za-z0-9_-]{20,}"),
    re.compile(rb"AIza[A-Za-z0-9_-]{30,}"),
]
SECRET_NAMES = re.compile(r"(^\.env|\.pem$|\.key$|credentials|id_rsa)")


def keep(p: Path) -> bool:
    if not p.is_file() or p.is_symlink():
        return False
    if any(part in SKIP_NAMES for part in p.parts):
        return False
    if p.suffix in SKIP_SUFFIX:
        return False
    if SECRET_NAMES.search(p.name):
        return False
    return p.stat().st_size <= MAX_FILE


def add_tree(files: set[Path], rel: str) -> None:
    base = ROOT / rel
    if not base.is_dir():
        return
    files.update(p for p in base.rglob("*") if keep(p))


def newest_dir(pattern: str) -> Path | None:
    hits = sorted(d for d in ROOT.glob(pattern) if d.is_dir())
    return hits[-1] if hits else None


def collect() -> tuple[list[Path], list[str]]:
    files: set[Path] = set()
    notes: list[str] = []

    missing = [r for r in REQUIRED if not (ROOT / r).is_file()]
    if missing:
        raise FileNotFoundError("required file missing: " + ", ".join(missing))
    files.update(ROOT / r for r in REQUIRED)

    for rel in ROOT_FILES:
        p = ROOT / rel
        if p.is_file():
            files.add(p)
        else:
            notes.append(f"absent: {rel}")

    for rel in TREES:
        add_tree(files, rel)

    for pattern in NEWEST_TREES:
        d = newest_dir(pattern)
        if d is None:
            notes.append(f"absent: {pattern}")
        else:
            add_tree(files, str(d.relative_to(ROOT)))
            notes.append(f"newest: {d.relative_to(ROOT)}")

    for pattern in SINGLE_GLOBS:
        hits = [p for p in ROOT.glob(pattern) if keep(p)]
        if not hits:
            notes.append(f"absent: {pattern}")
        files.update(hits)

    for pattern in (PNR_REPORTS, PNR_LOGS):
        for d in ROOT.glob(pattern):
            if d.is_dir():
                files.update(p for p in d.rglob("*") if keep(p))

    total = sum(p.stat().st_size for p in files)
    if total > MAX_TOTAL:
        big = sorted(files, key=lambda p: -p.stat().st_size)[:5]
        raise RuntimeError(
            f"bundle would be {total / 1e9:.1f} GB -- a tool workdir has been "
            "swept in. Largest: " +
            ", ".join(f"{p.relative_to(ROOT)} ({p.stat().st_size / 1e6:.0f} MB)"
                      for p in big))
    notes.append(f"uncompressed: {total / 1e6:.1f} MB")
    return sorted(files), notes


def check_secrets(files: list[Path]) -> None:
    hits = []
    for p in files:
        data = p.read_bytes()
        if any(pat.search(data) for pat in SECRET_PATTERNS):
            hits.append(str(p.relative_to(ROOT)))
    if hits:
        raise RuntimeError("possible secret in: " + ", ".join(hits))


def main() -> int:
    ap = argparse.ArgumentParser()
    stamp = datetime.now().strftime("%Y%m%d")
    ap.add_argument("--out", type=Path, default=ROOT.parent /
                    f"Astera_Nebula_Digital_Timing_Blinders_{stamp}.zip")
    args = ap.parse_args()

    files, notes = collect()
    check_secrets(files)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in files:
            z.write(p, Path("digital") / p.relative_to(ROOT))

    digest = hashlib.sha256(args.out.read_bytes()).hexdigest()
    with zipfile.ZipFile(args.out) as z:
        bad = z.testzip()
    if bad:
        raise RuntimeError(f"ZIP CRC failed at {bad}")

    for n in notes:
        print(f"NOTE {n}")
    print(f"PACKAGE {args.out}")
    print(f"FILES {len(files)}")
    print(f"BYTES {args.out.stat().st_size}")
    print("SECRET_SCAN PASS")
    print("CRC PASS")
    print(f"SHA256 {digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
