/* Generated by Yosys 0.67+135 (git sha1 ac5910309-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module traffic_light(clk, rst_n, red, yellow, green);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output red;
  wire red;
  output yellow;
  wire yellow;
  output green;
  wire green;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [2:0] count;
  wire green_r;
  wire red_r;
  wire [1:0] state;
  wire yellow_r;
  sky130_fd_sc_hd__or3b_1 _22_ (
    .A(count[0]),
    .B(count[2]),
    .C_N(count[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2b_1 _23_ (
    .A_N(state[1]),
    .B(state[0]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _24_ (
    .A(_08_),
    .SLEEP(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand4bb_1 _26_ (
    .A_N(state[1]),
    .B_N(count[2]),
    .C(count[1]),
    .D(count[0]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(state[0]),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21a_1 _28_ (
    .A1(_10_),
    .A2(_13_),
    .B1(rst_n),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(_08_),
    .B(_09_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__or3_1 _30_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .X(_15_)
  );
  sky130_fd_sc_hd__nand2b_1 _31_ (
    .A_N(state[0]),
    .B(state[1]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o22ai_1 _32_ (
    .A1(state[0]),
    .A2(_12_),
    .B1(_15_),
    .B2(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _33_ (
    .A1(_08_),
    .A2(_09_),
    .B1(rst_n),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3_1 _35_ (
    .A(_17_),
    .B(_18_),
    .C(_19_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor3_1 _36_ (
    .A(count[0]),
    .B(_17_),
    .C(_18_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _37_ (
    .A(_15_),
    .SLEEP(_16_),
    .X(_20_)
  );
  sky130_fd_sc_hd__o21a_1 _38_ (
    .A1(_14_),
    .A2(_20_),
    .B1(rst_n),
    .X(_06_)
  );
  sky130_fd_sc_hd__o41ai_1 _39_ (
    .A1(_10_),
    .A2(_13_),
    .A3(_14_),
    .A4(_20_),
    .B1(rst_n),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _40_ (
    .A(count[2]),
    .B(_11_),
    .X(_21_)
  );
  sky130_fd_sc_hd__nor3_1 _41_ (
    .A(_17_),
    .B(_18_),
    .C(_21_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21a_1 _42_ (
    .A1(_10_),
    .A2(_13_),
    .B1(rst_n),
    .X(_04_)
  );
  sky130_fd_sc_hd__o21a_1 _43_ (
    .A1(_14_),
    .A2(_20_),
    .B1(rst_n),
    .X(_07_)
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_07_),
    .Q(yellow_r)
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_04_),
    .Q(green_r)
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_03_),
    .Q(red_r)
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_00_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_06_),
    .Q(state[1])
  );
  assign green = green_r;
  assign yellow = yellow_r;
  assign red = red_r;
endmodule
